### ISSUE TITLE
Got old empty files

### ISSUE THREAD

**Issue by TimerWolf** [ciubex/dscautorename#1]
Hay, i was in my phone today on the computer and notice i got alot of DSC_XXXX that not has been deleted, I´m not sure if the program has rename the others and failed to just delete this ones or if it have try to rename them and somehow just trash the files I´m not sure actually

I have it set now to rename the files 0s after them has been taken, but the camera app i have in my "Xperia Z3+/Z4" just show me first the the file i just take can´t be used or not exist. And after some seconds it found it when its renamed and the mobile have find the new filename.

I´m not sure if its anyway around this problem

\ Anton

**Comment by ciubex** [comment]
Hi Anton,
Did you updated the application or you installed recently?First I recommend you to uninstall the application and then reinstall it.Try to reproduce your scenarios and if is still reproducible please send me logs from the application using "Send debugging logs".
Regards,Claudiu
