### ISSUE TITLE
About translation

### ISSUE THREAD

**Issue by naofum** [ciubex/dscautorename#3]
Hello ciubex!
I translated into Japanese on Weblate.
Would you please merge that?
Best,

**Comment by ciubex** [comment]
Hi, I forgot about Weblate.
I posted for translations another page: https : //www.localize.im/projects/pn (do not use this anymore, for translations please use Weblate: https://hosted.weblate.org/projects/dsc-auto-rename/strings )
I will import Japanese translation from Weblate.

Thanks!

**Comment by ciubex** [comment]
I changed the translation support to use the Weblate platform.
Thank you Naofum for your contribution!
