### ISSUE TITLE
Make licensing more visible

### ISSUE THREAD

**Issue by ghost** [ciubex/dscautorename#4]
While the source files have GPLv3+ headers, it would be nice to have a statement added to the readme or have a COPYING/LICENSE file. This will make the licensing more visible as well as covering all parts of the app, not just individual source files.

**Comment by ciubex** [comment]
The licence file is included in sources too: https://github.com/ciubex/dscautorename/blob/master/assets/gpl-3.0-standalone.html

It is visible on the application too.

I will add a reference in the README.MD file also.

**Comment by ciubex** [comment]
I modified the README.md file
